### ISSUE TITLE
thread 'main' panicked at src/main.rs:314:17

### ISSUE THREAD

**Issue by jvoisin** [AsahiLinux/speakersafetyd#16]
I was idling looking at `journalctl` when I saw the following messages:

```
Sep 03 21:43:25 chernabog speakersafetyd[1398]: thread 'main' panicked at src/main.rs:314:17:
Sep 03 21:43:25 chernabog speakersafetyd[1398]: Invalid sample rate
Sep 03 21:43:25 chernabog speakersafetyd[1398]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Sep 03 21:43:25 chernabog kernel: snd-soc-macaudio sound: Speaker volumes locked: Main control not locked
Sep 03 21:43:25 chernabog speakersafetyd[1398]: WARN  [speakersafetyd] Panic!
Sep 03 21:43:25 chernabog speakersafetyd[1398]: WARN  [speakersafetyd::blackbox] Blackbox is empty, nothing to save
Sep 03 21:43:25 chernabog systemd[1]: speakersafetyd.service: Main process exited, code=exited, status=101/n/a
Sep 03 21:43:25 chernabog systemd[1]: speakersafetyd.service: Failed with result 'exit-code'.
```

```
jvoisin@chernabog 00:29 ~ speakersafetyd --version
speakersafetyd 0.1.9
jvoisin@chernabog 00:29 ~ 
```

# Asahi Linux System Diagnostic Dump

    Collected at:   Wed  4 Sep 00:27:33 CEST 2024 (2024-09-04T00:27:33+02:00)
    Username:       jvoisin
    Hostname:       chernabog

## Device information
    Model:          Apple MacBook Air (13-inch, M2, 2022)
    Compatible:     apple,j413 apple,t8112 apple,arm-platform

## Firmware versions
    iBoot1:         iBoot-10151.140.19
    iBoot2:         iBoot-8422.141.2
    SFR:            unknown
    OS firmware:    13.5
    m1n1 stage 2:   v1.4.14
    U-Boot:         2024.04

## Boot information
    ESP UUID:       f0f3e299-07aa-4db9-a3fe-965e5969237a
    EFI:            available

## System information
    Distro:         Fedora Linux Asahi Remix 40 (Workstation Edition)
    Kernel:         6.10.6-401.asahi.fc40.aarch64+16k
    Kernel build:   #1 SMP PREEMPT_DYNAMIC Sat Aug 24 16:13:13 UTC 2024
    Uptime:          00:27:33 up  2:44,  1 user,  load average: 0.46, 0.63, 0.66
    Kernel cmdline: BOOT_IMAGE=(hd0,gpt5)/vmlinuz-6.10.6-401.asahi.fc40.aarch64+16k root=UUID=6b7fba8b-c7ab-48fe-b5b2-a3ce1dc9476f ro rootflags=subvol=root rhgb quiet rootflags=subvol=root rd.luks.uuid=2cae1ea9-2f69-4e31-9b28-d0d236fe3d5c brcmfmac.feature_disable=0x82000

## Audio Configuration:
    Default profile: 
    Pro Audio profile detected: no
    Old configuration files in `/etc/`: no
    File conflicts in `/usr/share/`: no
    Speaker detonation requested: no
    TAS2764 quirks applied: yes

## Environment
    COLORTERM=truecolor
    DISPLAY=:0
    GDM_LANG=en_GB.UTF-8
    GNOME_SETUP_DISPLAY=:1
    LANG=en_GB.UTF-8
    LANGUAGE=en_GB.UTF-8
    LC_ADDRESS=fr_FR.UTF-8
    LC_ALL=en_GB.UTF-8
    LC_MEASUREMENT=fr_FR.UTF-8
    LC_MONETARY=fr_FR.UTF-8
    LC_NUMERIC=fr_FR.UTF-8
    LC_PAPER=fr_FR.UTF-8
    LC_TELEPHONE=fr_FR.UTF-8
    LC_TIME=fr_FR.UTF-8
    TERM=xterm-256color
    WAYLAND_DISPLAY=wayland-0
    XDG_SESSION_TYPE=wayland

## Mounts
```
/dev/mapper/fedora-root / btrfs rw,seclabel,relatime,compress=zstd:1,ssd,space_cache=v2,subvolid=256,subvol=/root 0 0
vendorfw /usr/lib/firmware/vendor tmpfs rw,seclabel,relatime,mode=755,inode64 0 0
devtmpfs /dev devtmpfs rw,seclabel,nosuid,size=4096k,nr_inodes=756426,mode=755,inode64 0 0
tmpfs /dev/shm tmpfs rw,seclabel,nosuid,nodev,inode64 0 0
devpts /dev/pts devpts rw,seclabel,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
sysfs /sys sysfs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
cgroup2 /sys/fs/cgroup cgroup2 rw,seclabel,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot 0 0
pstore /sys/fs/pstore pstore rw,seclabel,nosuid,nodev,noexec,relatime 0 0
efivarfs /sys/firmware/efi/efivars efivarfs ro,nosuid,nodev,noexec,relatime 0 0
bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /run tmpfs rw,seclabel,nosuid,nodev,size=4862896k,nr_inodes=819200,mode=755,inode64 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,nosuid,noexec,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=37,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=11632 0 0
mqueue /dev/mqueue mqueue rw,seclabel,nosuid,nodev,noexec,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,seclabel,nosuid,nodev,relatime,pagesize=32M 0 0
tracefs /sys/kernel/tracing tracefs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
none /sys/kernel/debug debugfs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
/dev/mapper/fedora-root /home btrfs rw,seclabel,relatime,compress=zstd:1,ssd,space_cache=v2,subvolid=257,subvol=/home 0 0
tmpfs /tmp tmpfs rw,seclabel,nosuid,nodev,nr_inodes=1048576,inode64 0 0
/dev/nvme0n1p5 /boot ext4 rw,seclabel,relatime 0 0
/dev/nvme0n1p4 /boot/efi vfat rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=winnt,errors=remount-ro 0 0
sunrpc /var/lib/nfs/rpc_pipefs rpc_pipefs rw,relatime 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /run/user/1000 tmpfs rw,seclabel,nosuid,nodev,relatime,size=2431440k,nr_inodes=607860,mode=700,uid=1000,gid=1000,inode64 0 0
portal /run/user/1000/doc fuse.portal rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
```

## Package versions
```
alsa-ucm-asahi-5-3.fc40.noarch
asahi-audio-2.3-1.fc40.noarch
asahi-platform-metapackage-0-13.fc40.aarch64
asahi-repos-1-13.fc40.noarch
dracut-asahi-20240822-3.fc40.noarch
fedora-asahi-remix-scripts-20240722-1.fc40.noarch
kernel-16k-6.10.5-400.asahi.fc40.aarch64
kernel-16k-6.10.6-401.asahi.fc40.aarch64
kernel-16k-6.9.12-401.asahi.fc40.aarch64
kernel-16k-modules-extra-6.10.5-400.asahi.fc40.aarch64
kernel-16k-modules-extra-6.10.6-401.asahi.fc40.aarch64
kernel-16k-modules-extra-6.9.12-401.asahi.fc40.aarch64
m1n1-1.4.14-3.fc40.aarch64
package asahi-fwextract is not installed
package mesa is not installed
pipewire-1.0.7-2.fc40.aarch64
speakersafetyd-0.1.9-3.fc40.aarch64
tiny-dfr-0.2.0-5.fc40.aarch64
uboot-images-armv8-2024.04-4.fc40.noarch
update-m1n1-20240822-3.fc40.noarch
wireplumber-0.5.5-1.fc40.aarch64
```

## Block devices
```
NAME            MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
zram0           252:0    0     8G  0 disk  [SWAP]
nvme0n1         259:0    0 465.9G  0 disk  
├─nvme0n1p1     259:1    0   500M  0 part  
├─nvme0n1p2     259:2    0  62.6G  0 part  
├─nvme0n1p3     259:3    0   2.3G  0 part  
├─nvme0n1p4     259:4    0   500M  0 part  /boot/efi
├─nvme0n1p5     259:5    0     1G  0 part  /boot
├─nvme0n1p6     259:6    0   394G  0 part  
│ └─fedora-root 253:0    0   394G  0 crypt /home
│                                          /
└─nvme0n1p7     259:7    0     5G  0 part  
nvme0n2         259:8    0     3M  0 disk  
nvme0n3         259:9    0   128M  0 disk  
```

/usr/sbin/asahi-diagnose: line 148: lspci: command not found
## PCI devices
```

```

## Input devices
```
I: Bus=0019 Vendor=05ac Product=0351 Version=0240
N: Name="Apple MTP multi-touch"
P: Phys=24eb30000.input.1 (multi-touch)
S: Sysfs=/devices/platform/soc/24eb14000.fifo/24eb30000.input/0019:05AC:0351.0002/input/input0
U: Uniq=F0T4085119S0V7CA6+MNG
H: Handlers=mouse0 event0 
B: PROP=5
B: EV=1b
B: KEY=e520 10000 0 0 0 0
B: ABS=67f800001000003
B: MSC=10

I: Bus=0019 Vendor=05ac Product=0351 Version=0240
N: Name="Apple MTP keyboard"
P: Phys=24eb30000.input.2 (keyboard)
S: Sysfs=/devices/platform/soc/24eb14000.fifo/24eb30000.input/0019:05AC:0351.0003/input/input1
U: Uniq=F0T4085119S0V7CA6+MNG
H: Handlers=sysrq kbd leds event1 
B: PROP=0
B: EV=120013
B: KEY=10000 0 0 0 101007b02011007 ff9f21fac14057ff ffbeffdfffefffff fffffffffffffffe
B: MSC=10
B: LED=1f

I: Bus=0003 Vendor=1050 Product=0407 Version=0110
N: Name="Yubico YubiKey OTP+FIDO+CCID"
P: Phys=usb-xhci-hcd.0.auto-1/input0
S: Sysfs=/devices/platform/soc/502280000.usb/xhci-hcd.0.auto/usb1/1-1/1-1:1.0/0003:1050:0407.0006/input/input2
U: Uniq=
H: Handlers=sysrq kbd leds event2 
B: PROP=0
B: EV=120013
B: KEY=e080ffdf01cfffff fffffffffffffffe
B: MSC=10
B: LED=1f

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="Apple SMC power/lid events"
P: Phys=macsmc-hid (0)
S: Sysfs=/devices/platform/soc/23e400000.smc/macsmc-hid/input/input3
U: Uniq=
H: Handlers=kbd event3 
B: PROP=0
B: EV=23
B: KEY=10000000000000 0
B: SW=1

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="MacBook Air J413 Headphone Jack"
P: Phys=ALSA
S: Sysfs=/devices/platform/sound/sound/card0/input4
U: Uniq=
H: Handlers=event4 
B: PROP=0
B: EV=21
B: SW=14
```

## Loaded modules
```
Module                  Size  Used by
rfcomm                131072  4
snd_seq_dummy          49152  0
snd_hrtimer            49152  1
snd_seq               147456  7 snd_seq_dummy
snd_seq_device         49152  1 snd_seq
nft_fib_inet           49152  1
nft_fib_ipv4           49152  1 nft_fib_inet
nft_fib_ipv6           49152  1 nft_fib_inet
nft_fib                49152  3 nft_fib_ipv6,nft_fib_ipv4,nft_fib_inet
nft_reject_inet        49152  10
nf_reject_ipv4         49152  1 nft_reject_inet
nf_reject_ipv6         65536  1 nft_reject_inet
nft_reject             49152  1 nft_reject_inet
nft_ct                 49152  7
nft_chain_nat          49152  3
nf_nat                 98304  1 nft_chain_nat
nf_conntrack          212992  2 nf_nat,nft_ct
nf_defrag_ipv6         65536  1 nf_conntrack
nf_defrag_ipv4         49152  1 nf_conntrack
binfmt_misc            65536  1
tun                    98304  2
brcmfmac_wcc           49152  0
ip_set                 98304  0
nf_tables             360448  286 nft_ct,nft_reject_inet,nft_fib_ipv6,nft_fib_ipv4,nft_chain_nat,nft_reject,nft_fib,nft_fib_inet
bnep                   65536  2
qrtr                   81920  2
sunrpc                770048  1
brcmfmac              491520  1 brcmfmac_wcc
brcmutil               49152  1 brcmfmac
hci_bcm4377            65536  0
cfg80211             1163264  1 brcmfmac
bluetooth             917504  30 hci_bcm4377,bnep,rfcomm
rfkill                 49152  7 bluetooth,cfg80211
appledrm               49152  1
snd_soc_macaudio       65536  7
macsmc_hid             49152  0
apple_isp             131072  0
ofpart                 65536  0
snd_soc_tas2764        49152  4
snd_soc_apple_mca      49152  1
snd_soc_cs42l84        65536  1
videobuf2_dma_sg       49152  1 apple_isp
videobuf2_memops       65536  1 videobuf2_dma_sg
videobuf2_v4l2         49152  1 apple_isp
spi_nor               196608  0
videodev              409600  2 videobuf2_v4l2,apple_isp
snd_soc_core          458752  4 snd_soc_apple_mca,snd_soc_cs42l84,snd_soc_macaudio,snd_soc_tas2764
videobuf2_common      114688  4 videobuf2_v4l2,videobuf2_dma_sg,apple_isp,videobuf2_memops
snd_compress           65536  1 snd_soc_core
mtd                   131072  3 spi_nor,ofpart
ac97_bus               49152  1 snd_soc_core
mc                    114688  4 videodev,videobuf2_v4l2,videobuf2_common,apple_isp
apple_soc_cpufreq      65536  0
leds_pwm               49152  0
joydev                 65536  0
fuse                  229376  3
loop                   65536  0
dm_multipath           81920  0
nfnetlink              49152  4 nf_tables,ip_set
zram                   65536  1
dm_crypt               81920  1
hid_apple              65536  0
nvmem_spmi_mfd         49152  6
tps6598x              131072  0
macsmc_hwmon           49152  0
rtc_macsmc             49152  0
macsmc_reboot          49152  0
dockchannel_hid        49152  0
gpio_macsmc            49152  2
macsmc_power           49152  0
simple_mfd_spmi        49152  0
crct10dif_ce           49152  1
apple_dcp             327680  1 appledrm
polyval_ce             49152  0
polyval_generic        49152  1 polyval_ce
ghash_ce               49152  0
mux_core               49152  1 apple_dcp
drm_dma_helper         49152  2 appledrm,apple_dcp
sha3_ce                49152  0
sha512_ce              49152  0
snd_pcm_dmaengine      49152  3 snd_soc_apple_mca,apple_dcp,snd_soc_core
sha512_arm64           49152  1 sha512_ce
snd_pcm               196608  8 snd_soc_apple_mca,snd_soc_cs42l84,apple_dcp,snd_compress,snd_soc_macaudio,snd_soc_core,snd_pcm_dmaengine
asahi                1196032  40
dwc3                  245760  2
ulpi                   65536  1 dwc3
phy_apple_atc          98304  12
snd_timer              81920  3 snd_seq,snd_hrtimer,snd_pcm
apple_dockchannel      49152  1 dockchannel_hid
apple_admac            65536  4
clk_apple_nco          49152  6
typec                 131072  2 phy_apple_atc,tps6598x
udc_core              114688  1 dwc3
apple_rtkit_helper     49152  0
pwm_apple              49152  1
macsmc_rtkit           49152  0
macsmc                 65536  7 macsmc_rtkit,macsmc_reboot,gpio_macsmc,macsmc_hid,macsmc_hwmon,macsmc_power,rtc_macsmc
snd                   163840  23 snd_seq,snd_seq_device,apple_dcp,snd_timer,snd_compress,snd_soc_macaudio,snd_soc_core,snd_pcm
spi_apple              49152  0
spmi_apple_controller    49152  0
pinctrl_apple_gpio     49152  6
nvmem_apple_efuses     49152  0
apple_wdt              49152  1
soundcore              49152  1 snd
i2c_pasemi_platform    49152  0
i2c_pasemi_core        65536  1 i2c_pasemi_platform
apple_dart             49152  11
xhci_plat_hcd          49152  0
vfat                   49152  1
fat                   114688  1 vfat
nvme_apple             65536  3
apple_sart             65536  1 nvme_apple
nvme_core             229376  4 nvme_apple
nvme_auth              65536  1 nvme_core
scsi_dh_rdac           49152  0
scsi_dh_emc            49152  0
scsi_dh_alua           49152  0
```

## Module parameters
    asahi
        debug_flags=0
        initial_tvb_size=8

    hid_apple
        fnmode=2
        iso_layout=-1
        swap_ctrl_cmd=0
        swap_fn_leftctrl=0
        swap_opt_cmd=0

    hid_magicmouse
        emulate_3button=Y
        emulate_scroll_wheel=Y
        report_undeciphered=N
        scroll_acceleration=N
        scroll_speed=32

**Comment by jvoisin** [comment]
And again today:

```
Nov 21 16:42:51 chernabog speakersafetyd[2328]: thread 'main' panicked at src/main.rs:310:17:
Nov 21 16:42:51 chernabog speakersafetyd[2328]: Invalid sample rate
Nov 21 16:42:51 chernabog speakersafetyd[2328]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 21 16:42:51 chernabog speakersafetyd[2328]: WARN  [speakersafetyd] Panic!
Nov 21 16:42:51 chernabog speakersafetyd[2328]: WARN  [speakersafetyd::blackbox] Blackbox is empty, nothing to save
```
