### ISSUE TITLE
thread 'main' panicked at src/main.rs:289:14:

### ISSUE THREAD

**Issue by jvoisin** [AsahiLinux/speakersafetyd#21]
```
Dec 30 01:50:42 chernabog pipewire[1662]: spa.alsa: hw:AppleJ413,1p: (0 suppressed) snd_pcm_avail after recover: Broken pipe
Dec 30 01:51:09 chernabog kernel: snd-soc-macaudio sound: Speaker volumes locked: Lock timeout
Dec 30 01:51:09 chernabog speakersafetyd[2220]: thread 'main' panicked at src/main.rs:289:14:
Dec 30 01:51:09 chernabog speakersafetyd[2220]: called `Result::unwrap()` on an `Err` value: ALSA function 'snd_pcm_readi' failed with error 'Broken pipe (32)'
Dec 30 01:51:09 chernabog speakersafetyd[2220]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Dec 30 01:51:09 chernabog speakersafetyd[2220]: WARN  [speakersafetyd] Panic!
Dec 30 01:51:09 chernabog speakersafetyd[2220]: WARN  [speakersafetyd::blackbox] Preserving blackbox 2024-12-30T01:51:09.447591225+01:00
Dec 30 01:51:09 chernabog systemd[1]: speakersafetyd.service: Main process exited, code=exited, status=101/n/a
Dec 30 01:51:09 chernabog systemd[1]: speakersafetyd.service: Failed with result 'exit-code'.
Dec 30 01:51:09 chernabog audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=speakersafetyd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Dec 30 01:51:09 chernabog systemd[1]: speakersafetyd.service: Consumed 5min 47.335s CPU time, 27.6M memory peak, 2.2M memory swap peak.
Dec 30 01:51:09 chernabog wireplumber[1663]: spa.audioconvert: 0xaaaad770b160: (0 suppressed) out of buffers on port 0 2
Dec 30 01:51:09 chernabog gnome-shell[1683]: libinput error: client bug: timer event0 keyboard: scheduled expiry is in the past (-27747ms), your system is too slow
Dec 30 01:51:10 chernabog systemd[1]: speakersafetyd.service: Scheduled restart job, restart counter is at 2.
Dec 30 01:51:10 chernabog systemd[1]: Started speakersafetyd.service - Speaker Protection Daemon.
```

[asahi-diagnose-20241230-022405.txt](https://github.com/user-attachments/files/18271439/asahi-diagnose-20241230-022405.txt)

**Comment by chadmed** [comment]
Was this after a suspend/resume with audio playing?

**Comment by jvoisin** [comment]
Nope, I was playing [Divinity: Original Sin](https://en.wikipedia.org/wiki/Divinity%3A_Original_Sin), it froze/lagged a bit at some point, then went back to normal.
